// Mocks generated by Mockito 5.4.4 from annotations
// in ditonton/test/presentation/provider/tv_show/detail_tv_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:ditonton/common/failure.dart' as _i6;
import 'package:ditonton/domain/entities/tv_entities/detail/tv_detail_model.dart'
    as _i7;
import 'package:ditonton/domain/entities/tv_entities/tv_list_model.dart' as _i9;
import 'package:ditonton/domain/repositories/tv_repository.dart' as _i2;
import 'package:ditonton/domain/usecases/tv_show/get_tv_show_detail.dart'
    as _i4;
import 'package:ditonton/domain/usecases/tv_show/get_tv_show_recomendation.dart'
    as _i8;
import 'package:ditonton/domain/usecases/tv_show/get_watchlist_tv_status.dart'
    as _i10;
import 'package:ditonton/domain/usecases/tv_show/remove_watchlist_tv.dart'
    as _i12;
import 'package:ditonton/domain/usecases/tv_show/save_watchlist_tv.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTvRepository_0 extends _i1.SmartFake implements _i2.TvRepository {
  _FakeTvRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetTvShowDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvShowDetail extends _i1.Mock implements _i4.GetTvShowDetail {
  MockGetTvShowDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TvRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.TvDetailModel>> executeProcess(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeProcess,
          [id],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.TvDetailModel>>.value(
                _FakeEither_1<_i6.Failure, _i7.TvDetailModel>(
          this,
          Invocation.method(
            #executeProcess,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.TvDetailModel>>);
}

/// A class which mocks [GetTvShowRecomendation].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvShowRecomendation extends _i1.Mock
    implements _i8.GetTvShowRecomendation {
  MockGetTvShowRecomendation() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TvRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i9.TvListModel>> executeProcess(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeProcess,
          [id],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i9.TvListModel>>.value(
            _FakeEither_1<_i6.Failure, _i9.TvListModel>(
          this,
          Invocation.method(
            #executeProcess,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i9.TvListModel>>);
}

/// A class which mocks [GetWatchlistTvStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistTvStatus extends _i1.Mock
    implements _i10.GetWatchlistTvStatus {
  MockGetWatchlistTvStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TvRepository);

  @override
  _i5.Future<bool> execute(int? id) => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [SaveWatchlistTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlistTv extends _i1.Mock implements _i11.SaveWatchlistTv {
  MockSaveWatchlistTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TvRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> execute(
          _i7.TvDetailModel? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [data],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, String>>.value(
            _FakeEither_1<_i6.Failure, String>(
          this,
          Invocation.method(
            #execute,
            [data],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, String>>);
}

/// A class which mocks [RemoveWatchlistTv].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlistTv extends _i1.Mock implements _i12.RemoveWatchlistTv {
  MockRemoveWatchlistTv() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TvRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeTvRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.TvRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> execute(
          _i7.TvDetailModel? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [data],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, String>>.value(
            _FakeEither_1<_i6.Failure, String>(
          this,
          Invocation.method(
            #execute,
            [data],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, String>>);
}
