// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI3Ou-Qoe0T3b2nWbqHdu7z833wNzgVag',
    appId: '1:958276061013:web:3ebaf41ba15560c43b51dc',
    messagingSenderId: '958276061013',
    projectId: 'ditonton-app-cbf75',
    authDomain: 'ditonton-app-cbf75.firebaseapp.com',
    storageBucket: 'ditonton-app-cbf75.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAuMqZ1CVIrl7UPk-JB65QVfX9Z_8MJxc',
    appId: '1:958276061013:android:8ac194e89e2e10d33b51dc',
    messagingSenderId: '958276061013',
    projectId: 'ditonton-app-cbf75',
    storageBucket: 'ditonton-app-cbf75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA44t_uVVRiXkBT6tSYZfUd9niVnK6hOE',
    appId: '1:958276061013:ios:5f34fcc192ca59ba3b51dc',
    messagingSenderId: '958276061013',
    projectId: 'ditonton-app-cbf75',
    storageBucket: 'ditonton-app-cbf75.firebasestorage.app',
    iosBundleId: 'com.dicoding.ditonton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA44t_uVVRiXkBT6tSYZfUd9niVnK6hOE',
    appId: '1:958276061013:ios:5f34fcc192ca59ba3b51dc',
    messagingSenderId: '958276061013',
    projectId: 'ditonton-app-cbf75',
    storageBucket: 'ditonton-app-cbf75.firebasestorage.app',
    iosBundleId: 'com.dicoding.ditonton',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI3Ou-Qoe0T3b2nWbqHdu7z833wNzgVag',
    appId: '1:958276061013:web:e84202d1f2ea10993b51dc',
    messagingSenderId: '958276061013',
    projectId: 'ditonton-app-cbf75',
    authDomain: 'ditonton-app-cbf75.firebaseapp.com',
    storageBucket: 'ditonton-app-cbf75.firebasestorage.app',
  );
}
